### ISSUE TITLE
My Maps

### ISSUE THREAD

**Issue by Darklightus** [googlemaps/js-store-locator#10]
With the new My Maps system, how does one use this?

For example, if I make a map with My Maps, how can I use the locations on the map in this library?
It seems near impossible to just import it to a table and such, it's nowhere to be found.

**Comment by darzo27** [comment]
@Wysaard Were you able to find a solution to integrating your own map with this framework?

**Comment by Wysaard** [comment]
@darzo27 I was. I worked at a company at that time and left all related code with them, so I couldn't provide it anymore I'm afraid.

The way I did it was by making a script that would convert the maps export format to a format compatible with this framework (csv I believe), and used a cronjob to update the data daily.

**Comment by darzo27** [comment]
@Wysaard That's cool. So you created a work-around for not using the API entirely then hey? 
I'm struggling with implementing a smaller map that I've created, into a larger map at the moment for a large college project, making very slow headway with the map aspect though!

**Comment by Wysaard** [comment]
@darzo27 Yeah. We had a client who wanted to advertise which shops were selling his stuff using maps. I couldn't get the function to fetch date from the web to work, but pulling info from a csv file was easy enough, so using cronjobs I did the web->csv and then used that for the store-locator.

I don't know if it's still that easy though, apps like these constantly change, but it worked at the time.
