### ISSUE TITLE
Limiting the amount of stores

### ISSUE THREAD

**Issue by Darklightus** [googlemaps/js-store-locator#11]
Is there a way to (only after entering your location or having determined it via geolocation) only show the x closest stores? Such that no stores are shown until you enter your address?

**Comment by leduc81** [comment]
Hi @Wysaard ! Did you find a solution ? Thanks!

**Comment by Wysaard** [comment]
@leduc81 I think I ended up hacking around in the JS for a bit and moved the function call that displays the scores to somewhere the interpreter would get only after the address has been entered. But I'm afraid this was at a company where I have left over a year ago and I did not have any copies of the code myself. So I'm afraid I can't really go into more detail as I don't have the code.
