### ISSUE TITLE
Clarify whether this library depends on Google Maps Engine

### ISSUE THREAD

**Issue by owenblacker** [googlemaps/js-store-locator#12]
The documentation for [storeLocator.GMEDataFeed](https://googlemaps.github.io/js-store-locator/reference.html#storeLocator.GMEDataFeed) suggests that this library relies on Google Maps Engine to provide a DataFeed of stores to search within.

Looking at the Google Maps Engine API documentation, however, shows that this is deprecated now:

> Note: The Google Maps Engine API is deprecated. Support for the Google Maps Engine (GME) product ends on January 29th, 2016. You can use your existing GME project as well as the GME API until that date. **After January 29th, 2016, GME will be deactivated and the API will therefore no longer be available.**

Does this library rely on GME — in which case it will stop working in less than a week — or have I misunderstood?

**Comment by domesticmouse** [comment]
This project is in an unmaintained state. I suggest you look at our [Google Maps APIs Solutions](https://developers.google.com/maps/solutions/) for currently maintained store locator solutions.
