### ISSUE TITLE
Set zoom level when store clicked and increasing number of results returned on initial map load

### ISSUE THREAD

**Issue by Tfx77** [googlemaps/js-store-locator#13]
Couple of thinks I am trying to change. 

1) Map is zoomed in when I click a store, how is this changed? I would have though the method in the store-locator.js this.filter_.submit(function()) would set this in the part (d.setCenter(b.geometry.location),d.setZoom(13));

2) When the map loads at the start, it only seems to return the top 9 results and I would like to increase this (I only have 20 or so locations so I am fine them all being pulled back.

**Comment by Tfx77** [comment]
I figured out point 2, the following needs changing, where 10 becomes the number you would like to pull back (solution found from another post) : 

for(var b=function(){a.highlight(this.store,!0)},e=0,f=Math.min(10,c.length)

**Comment by GeneralRamy** [comment]
@Tfx77  how can i return all items ? which file you updated ?

**Comment by Tfx77** [comment]
store-locator.js

I would just set the amount returned to a high number if you want to return *all*. Not sure if this would cause errors or pull back empty result sets (you would have to try) as it is just a simple loop.

**Comment by GeneralRamy** [comment]
i change this part`f=Math.min(10,c.length);` to be `f=c.length` to get all , Thanks

**Comment by domesticmouse** [comment]
This project is in an unmaintained state. I suggest you look at our [Google Maps APIs Solutions](https://developers.google.com/maps/solutions/) for currently maintained store locator solutions.
