### ISSUE TITLE
Only 10 stores are pulled back on the front end

### ISSUE THREAD

**Issue by liamrf** [googlemaps/js-store-locator#14]
Hi there,

I'm using this on my site and it's great. The problem I have is I have more than 10 stores, but the locator only shows a maximum of 10 stores on the the stores list. I'm attempting to make an amendment so that all stores are picked up in the list. Is this possible?

Thanks

**Comment by teej043** [comment]
I am wondering why is there a limit and why an option to the stores list visibility is not exposed to the example codes. 

The least I can do was to find that static number "10" somewhere in the store-locator.min.js, I found it and I edit it to "20" and now it shows 20 stores in the list. I only hope there was a better approach on this.

**Comment by abhi11210646** [comment]
Hey Guys,
I have created same application for medical store and it is working fine there is no store restriction. You may check here..demo.
 http://howru.tk/kashish/

and repo:-   https://github.com/abhi11210646/customize-map-using-Google-place-API-to-find-medical-store

you may fork it and enjoy.

**Comment by teej043** [comment]
@abhi11210646 

Thanks bro, but will it work with the static data source? I see that your example is based on the google places api, but I am using static json data, also the 10 limit is evident on csv example as well.

**Comment by f3ndot** [comment]
Dealt with in #21

**Comment by enderoe** [comment]
Cant get the #21 fix in a static library.

**Comment by kirandash** [comment]
@liamrf 

On https://github.com/googlemaps/js-store-locator/blob/gh-pages/dist/store-locator.min.js

Inside `storeLocator.Panel.prototype.stores_changed` function

`for(var b=function(){a.highlight(this.store,!0)},e=0,f=Math.min(10,c.length);e<f;e++)`

Here,

`f=Math.min(10,c.length)`

is the code that sets the limit for how many stores are going to be shown on the panel.

Just change the value of f to change the limit on number of stores to be shown in panel. If you want to show 30 stores just change the code to 

`for(var b=function(){a.highlight(this.store,!0)},e=0,f=20;e<f;e++)`

and you should be good.

**Comment by domesticmouse** [comment]
This project is in an unmaintained state. I suggest you look at our [Google Maps APIs Solutions](https://developers.google.com/maps/solutions/) for currently maintained store locator solutions.
