### ISSUE TITLE
Accessing map from other script

### ISSUE THREAD

**Issue by kimek** [googlemaps/js-store-locator#15]
Can we make variable with google map instance as window.jsStoreLocator to access it from other scripts ? 
This partly request/issue as I am not able to use autocomplete for filtering pubs by name I use external script to populated list from json and Im using js-store-locator only to find pubs by postcode in same 'input field'.

**Comment by domesticmouse** [comment]
This project is in an unmaintained state. I suggest you look at our [Google Maps APIs Solutions](https://developers.google.com/maps/solutions/) for currently maintained store locator solutions.
