### ISSUE TITLE
Scale the marker image according to zoom level

### ISSUE THREAD

**Issue by teej043** [googlemaps/js-store-locator#16]
I have added a listener for the zoom event and capture zoom level, however I couldn't get to update the view to make store markers use another marker image (smaller image for zoom level 9 and up).

Is there a way to do this?

**Comment by domesticmouse** [comment]
This project is in an unmaintained state. I suggest you look at our [Google Maps APIs Solutions](https://developers.google.com/maps/solutions/) for currently maintained store locator solutions.
