### ISSUE TITLE
Hard coded features list

### ISSUE THREAD

**Issue by teej043** [googlemaps/js-store-locator#17]
Is there a way so that the features list comes from a data source like json? Apparently, the example shows that you need to hardcode the features e.g:

```
JwStoresDataSource.prototype.FEATURES_ = new storeLocator.FeatureSet(
  new storeLocator.Feature('Category-4122', 'Exhibition'),
  new storeLocator.Feature('Category-4144', 'Catalog'),
  new storeLocator.Feature('Category-4145', 'Sales'),
  new storeLocator.Feature('Category-4146', 'Installer'),
  new storeLocator.Feature('Category-4147', 'Maintenance')
);
```

I'm using the static data json approach, and I added the feature lists on the json that I can use to populate the list of features, but I can't seem to do it since the adding of single feature is by way of specifying via arguments, as seen on the code above.

It would've been great if I could just specify an array variable as argument to it, this array will have all the features (each with id and name) that came from json.

Any ideas?

**Comment by domesticmouse** [comment]
This project is in an unmaintained state. I suggest you look at our [Google Maps APIs Solutions](https://developers.google.com/maps/solutions/) for currently maintained store locator solutions.
