### ISSUE TITLE
Costs - Google Maps use ?

### ISSUE THREAD

**Issue by timrrice** [googlemaps/js-store-locator#18]
I'm a newbie and asking what may seem a naive question but I don't want to get stung with costs (from GOOGLE).
If I use the "Store Locator" plug-in are there any fees / licences / costs involved from GOOGLE.
I understand yours is free (and yes I will make a contribution) but its more what it accesses / plugs into that I'm concerned about. Any comments appreciated ......

**Comment by domesticmouse** [comment]
This project is in an unmaintained state. I suggest you look at our [Google Maps APIs Solutions](https://developers.google.com/maps/solutions/) for currently maintained store locator solutions.
