### ISSUE TITLE
Decouple geocode listener from locationSearch option conditional

### ISSUE THREAD

**Issue by psullivan6** [googlemaps/js-store-locator#19]
Currently I am trying to leverage a `Panel` to display a list of stores, but with a search input that is in a custom DOM element not contained within the `Panel` element. To achieve this goal, I have thought of 2 potential solutions:
1. Pass a custom DOM element via the locationSearch setting and override the default private `locationSearch_` variable
2. Disable the default location search via `locationSearch: false` and call the `searchPosition` function via the custom DOM element's `click` listener or similar.

I am inclined to go with option 2 as it seems to cause less of a headache, but I have found that the `geocode` listener that is triggered by the `searchPosition` call is contained within a conditional check of the `locationSearch` setting, thus disabling its functionality if `locationSearch: false` is set. Considering there are a few private functions contained within the [listener's callback](https://github.com/googlemaps/js-store-locator/blob/gh-pages/js/panel.js#L97-L119) I don't want to just copy/paste that code (not that I would anyway). I am inclined to think that moving the [geocode listener](https://github.com/googlemaps/js-store-locator/blob/gh-pages/js/panel.js#L97-L119) block outside the `if (this.settings_['locationSearch']) {...` conditional will solve the problem, but I am not aware of other potential repercussions of this action, hence the ticket and not a pull request ;)

Please let me know if there is an easy way to leverage a search field outside the scope of the `Panel` DOM element or if either of the above solutions seem feasible.

**Comment by domesticmouse** [comment]
This project is in an unmaintained state. I suggest you look at our [Google Maps APIs Solutions](https://developers.google.com/maps/solutions/) for currently maintained store locator solutions.
