### ISSUE TITLE
Unable to feed the data

### ISSUE THREAD

**Issue by pranireddy9** [googlemaps/js-store-locator#23]
Hi,

I am writing a sample to pinpoint the locations on the map. 
I have imported the project and ran it. its working fine. but i am unable to feed my data(store locations). its just simply showing the map not the locations. how can i feed data can anyone please help me on this?

**Comment by mukta122** [comment]
Hi,

I am writing a sample to pinpoint the locations on the map.
I have imported the project and ran it. its working fine. but i am unable to feed my data(store locations). its just simply showing the map not the locations. how can i feed data can anyone please help me on this?

**Comment by domesticmouse** [comment]
This project is in an unmaintained state. I suggest you look at our [Google Maps APIs Solutions](https://developers.google.com/maps/solutions/) for currently maintained store locator solutions.
