### ISSUE TITLE
MissingKeyMapError

### ISSUE THREAD

**Issue by slepit** [googlemaps/js-store-locator#24]
Hello,

I have just downloaded your examples. 

When I try to run
examples/panel.html
I get the following error : Google Maps API error: MissingKeyMapError 

I tried to change the key in some of the javascript file but did not solve the error.

**Comment by dkutcher** [comment]
Any resolution here?

**Comment by domesticmouse** [comment]
This project is in an unmaintained state. I suggest you look at our [Google Maps APIs Solutions](https://developers.google.com/maps/solutions/) for currently maintained store locator solutions.
