### ISSUE TITLE
Reference Documentation Style is missing

### ISSUE THREAD

**Issue by nahidacm** [googlemaps/js-store-locator#25]
Seems the style-sheet of https://googlemaps.github.io/js-store-locator/reference.html
is missing.

From browser console:
https://developers.google.com/_static/css/screen-docs.css Failed to load resource: the server responded with a status of 404 ()

**Comment by domesticmouse** [comment]
This project is in an unmaintained state. I suggest you look at our [Google Maps APIs Solutions](https://developers.google.com/maps/solutions/) for currently maintained store locator solutions.
