### ISSUE TITLE
AngularJS

### ISSUE THREAD

**Issue by kamilszmit** [googlemaps/js-store-locator#27]
How to use "js-store-locator" in AngularJS? I can install it with command "bower install js-store-locator --save". Should I add something to "angular.module.js"? Should I add some parameter to "Controller" function of a page? What variables should I use in "controller" function?

**Comment by domesticmouse** [comment]
This project is in an unmaintained state. I suggest you look at our [Google Maps APIs Solutions](https://developers.google.com/maps/solutions/) for currently maintained store locator solutions.
