### ISSUE TITLE
How to add own coordinates?

### ISSUE THREAD

**Issue by mungekarabhishek** [googlemaps/js-store-locator#29]
How to add our own coordinates into a map?
Also how to use json instead of csv file?

**Comment by lamarena** [comment]
Hi,

Thanks for purchasing our template. Below is instructions for google map.

*How to solve the Google map problem.*

Recently google has made a change that now on the Map will require API keys
to function.

Its easy to grab and setup API key here are the steps.

1) Obtain an API key using this URL https://developers.google.
com/maps/documentation/javascript/get-api-key

2) Edit the page in your favourite editor, where the map appears, eg
Contact.html, and find this line on the bottom : http://prntscr.com/bowg5s It
normally looks like this <script src=”http://maps.googleapis.
com/maps/api/js?sensor=false&language=en”></script>

3) Modify above line like this <script src=”http://maps.googleapis.
com/maps/api/js?key=YOUR_API_KEY&sensor=false&language=en”></script>

4) Replace Your_api_key with your actual key you obtained in step 1.
Thats it. If you need help, please contact support.



Thanks and Regards
*Lamarena*

**Comment by mungekarabhishek** [comment]
@lamarena This is not the answer of my question.I am not able to add own coordinates.
E.g. If i would like to add Location BSE of mumbai then how would i add it?
CSV not able to update it.

**Comment by lamarena** [comment]
Hi mungekarabhishek,

*https://www.youtube.com/watch?v=rcrYeNq4XkU
<https://www.youtube.com/watch?v=rcrYeNq4XkU>    *


This video tutorial may be usefull, please try to add your coordinates steb
by step.


Cheers,
Lamarena

On Thu, Apr 20, 2017 at 12:39 PM, mungekarabhishek <notifications@github.com

**Comment by mungekarabhishek** [comment]
@lamarena Thank you for the reply.
Also i would like to functionality like
 if I have 1000 stores, and the user enters their location, I really only want to list stores that are in a (for example) 5 mile radius of their location, rather than the default all stores, ordered from closest to nearest.

**Comment by domesticmouse** [comment]
@mungekarabhishek for some tutorials and samples that illustrate a variety of approaches to handling store locators with windowing, please see [Google Maps solutions](https://developers.google.com/maps/solutions/). Thanks!
