### ISSUE TITLE
Mobile?

### ISSUE THREAD

**Issue by IanDarwin** [googlemaps/js-store-locator#3]
Any plans to do a mobile variant where, e.g., a smaller version of the Canvas pops up over the Panel when you click on a location, or instead, just show the Canvas and not the Panel when you search?
(Bootstrap visibility classes would be the icing on the cake).

TIA

**Comment by nlambert** [comment]
+1 Came here searching for exactly this. 

On mobile, search bar and results suffice, so we have hidden the map. Were wondering if we could improve performance by not updating the map and linking to google maps directly on click.

**Comment by domesticmouse** [comment]
This project is in an unmaintained state. I suggest you look at our [Google Maps APIs Solutions](https://developers.google.com/maps/solutions/) for currently maintained store locator solutions.
