### ISSUE TITLE
Store locator does not work unless on a HTTPS site / without location permission

### ISSUE THREAD

**Issue by mattgreenfield** [googlemaps/js-store-locator#31]
I would expect the library to still work if the user hasn't given location permission, but to not provide the functionality that depends on it. At present, the map does not load unless permission is granted.

I can replicate this on local host by enabling and disabling location permissions.

This becomes even more of a problem when it is not hosted on HTTPS as modern browsers no longer allow location access on non HTTPS sites. In chrome I get the following warning when hosted on HTTP;
> store-locator.min.js:1 getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

Which is really more of an error than a warning as it prevents the map for loading.

Thanks.

**Comment by domesticmouse** [comment]
This project is in an unmaintained state. I suggest you look at our [Google Maps APIs Solutions](https://developers.google.com/maps/solutions/) for currently maintained store locator solutions.
