### ISSUE TITLE
Changing hardcoded text labels

### ISSUE THREAD

**Issue by bwente** [googlemaps/js-store-locator#4]
It would be nice to be able to edit the text in some places without the fear of losing it when updating. I thought I could do something like this in the mean time, but can't figure out where to place it.

```
$(".no-stores").text(function () {
    return $(this).text().replace(/stores/g, "parks");
});
```

**Comment by broady** [comment]
We should probably add an option for these strings!

**Comment by barryvdh** [comment]
Something like an array of messages, with defaults in english would be nice, so we could override them with translated messages or just different names.

**Comment by drskullster** [comment]
:+1: !

**Comment by domesticmouse** [comment]
This project is in an unmaintained state. I suggest you look at our [Google Maps APIs Solutions](https://developers.google.com/maps/solutions/) for currently maintained store locator solutions.
