### ISSUE TITLE
Showing multiple items with the filter

### ISSUE THREAD

**Issue by nuahssiaram** [googlemaps/js-store-locator#6]
When you tick multiple options on the filter, it doesn't list each option underneath each other. 
Any idea how to fix this?

http://www.icommunityafrica.com/wp-content/uploads/2015/04/Screen-Shot-2015-04-21-at-4.06.32-PM.png

**Comment by domesticmouse** [comment]
This project is in an unmaintained state. I suggest you look at our [Google Maps APIs Solutions](https://developers.google.com/maps/solutions/) for currently maintained store locator solutions.
