### ISSUE TITLE
Possible to apply filters to store list?

### ISSUE THREAD

**Issue by psykoptic** [googlemaps/js-store-locator#7]
I see the **distanceTo method** in the code, but is it possible to filter the store list (ul.store-list) so that it is only returning a subset of the data nearest the location?

eg, if I have 1000 stores, and the user enters their location, I really only want to list stores that are in a (for example) 20 mile radius of their location, rather than the default all stores, ordered from closest to nearest.

**Comment by leduc81** [comment]
Hey! I also need that @psykoptic , did you manage to find a solution ?

**Comment by mungekarabhishek** [comment]
Yes Have you got any solution? @psykoptic @leduc81 @broady @markmcd @domesticmouse

**Comment by domesticmouse** [comment]
This project is in an unmaintained state. I suggest you look at our [Google Maps APIs Solutions](https://developers.google.com/maps/solutions/) for currently maintained store locator solutions.
